#!/usr/bin/env python3
"""
Build a dated "failed tests" TestNG suite from a CI run's results.

Collects every test that FAILED across all module reports of a CI run and
writes ONE runnable TestNG suite — so you can re-run all failures locally in
one shot, and keep a dated history of what failed when.

Usage:
    # latest completed run of the parallel workflow:
    python3 .github/scripts/build-failed-suite.py

    # a specific run id:
    python3 .github/scripts/build-failed-suite.py --run 26881798303

    # parse already-downloaded results instead of fetching from GitHub:
    python3 .github/scripts/build-failed-suite.py --from /path/with/testng-results

    # override the date label (default = today):
    python3 .github/scripts/build-failed-suite.py --date 2026-06-03

Then run the failures locally:
    mvn test -DsuiteXmlFile=failed-suites/failed-<date>.xml

Output:
    failed-suites/failed-<date>.xml   — the runnable suite (overwritten per date)
    failed-suites/history.md          — appended log: date | count | run | classes
"""
import argparse
import glob
import os
import subprocess
import sys
import tempfile
from collections import defaultdict
from datetime import date

try:
    import defusedxml.ElementTree as ET  # XXE-safe
except ImportError:
    # Guarantee the safe parser rather than falling back to the vulnerable stdlib one.
    subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "defusedxml"])
    import defusedxml.ElementTree as ET

WORKFLOW = "iOS Tests - Full Parallel Suite"
REPO = "eg-abhiyantsingh/iOS_automation_site"
OUT_DIR = "failed-suites"


def sh(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def latest_run_id():
    r = sh(["gh", "run", "list", "--repo", REPO, "--workflow", WORKFLOW,
            "--status", "completed", "--limit", "1", "--json", "databaseId"])
    import json
    runs = json.loads(r.stdout or "[]")
    if not runs:
        sys.exit("No completed runs found for workflow: " + WORKFLOW)
    return str(runs[0]["databaseId"])


def download_run(run_id, dest):
    print(f"⤓ downloading artifacts for run {run_id} …")
    r = sh(["gh", "run", "download", run_id, "--repo", REPO, "--dir", dest])
    if r.returncode != 0:
        print(r.stderr.strip())
        sys.exit(f"Could not download artifacts for run {run_id} "
                 "(expired after 7 days, or run still in progress?)")


def collect_failures(results_dir):
    """Return {fqcn: set(methods)} for methods that FAILED and did not later PASS."""
    status = defaultdict(lambda: defaultdict(set))  # fqcn -> method -> {statuses}
    xmls = glob.glob(os.path.join(results_dir, "**", "testng-results.xml"), recursive=True)
    print(f"  parsed {len(xmls)} testng-results.xml file(s)")
    for xml in xmls:
        try:
            root = ET.parse(xml).getroot()
        except Exception as e:
            print(f"  ! skip {xml}: {e}")
            continue
        for cls in root.iter("class"):
            fqcn = cls.get("name")
            if not fqcn:
                continue
            for tm in cls.iter("test-method"):
                if tm.get("is-config") == "true":
                    continue
                name = tm.get("name")
                st = tm.get("status")
                if name and st:
                    status[fqcn][name].add(st)
    failures = defaultdict(set)
    for fqcn, methods in status.items():
        for method, sts in methods.items():
            # failed, and not a retry that eventually passed
            if "FAIL" in sts and "PASS" not in sts:
                failures[fqcn].add(method)
    return failures


def write_suite(failures, the_date, run_id):
    os.makedirs(OUT_DIR, exist_ok=True)
    total = sum(len(m) for m in failures.values())
    path = os.path.join(OUT_DIR, f"failed-{the_date}.xml")

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">',
             f'<suite name="Failed Tests {the_date} ({total} failures)" '
             f'verbose="0" time-out="480000">',
             '    <!-- Auto-generated by .github/scripts/build-failed-suite.py'
             f' from CI run {run_id}. Re-run locally: '
             f'mvn test -DsuiteXmlFile={path} -->',
             '    <listeners>',
             '        <listener class-name="com.egalvanic.listeners.ConsoleProgressListener"/>',
             '    </listeners>',
             f'    <test name="CI Failures {the_date}">',
             '        <classes>']
    for fqcn in sorted(failures):
        lines.append(f'            <class name="{fqcn}">')
        lines.append('                <methods>')
        for method in sorted(failures[fqcn]):
            lines.append(f'                    <include name="{method}"/>')
        lines.append('                </methods>')
        lines.append('            </class>')
    lines += ['        </classes>', '    </test>', '</suite>', '']
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path, total


def append_history(the_date, total, run_id, failures):
    os.makedirs(OUT_DIR, exist_ok=True)
    hist = os.path.join(OUT_DIR, "history.md")
    new = not os.path.exists(hist)
    per_class = ", ".join(f"{c.split('.')[-1]}:{len(m)}" for c, m in sorted(failures.items()))
    with open(hist, "a") as f:
        if new:
            f.write("# CI Failure History\n\n"
                    "Generated by `.github/scripts/build-failed-suite.py`.\n\n"
                    "| Date | Failures | Run | Breakdown |\n|---|---|---|---|\n")
        run_url = f"https://github.com/{REPO}/actions/runs/{run_id}"
        f.write(f"| {the_date} | {total} | [{run_id}]({run_url}) | {per_class or '—'} |\n")
    return hist


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", help="CI run id (default: latest completed)")
    ap.add_argument("--from", dest="src", help="parse a local results dir instead of fetching")
    ap.add_argument("--date", default=None, help="date label (default: today, ISO)")
    args = ap.parse_args()
    the_date = args.date or date.today().isoformat()

    if args.src:
        run_id = "local"
        failures = collect_failures(args.src)
    else:
        run_id = args.run or latest_run_id()
        with tempfile.TemporaryDirectory() as tmp:
            download_run(run_id, tmp)
            failures = collect_failures(tmp)

    path, total = write_suite(failures, the_date, run_id)
    hist = append_history(the_date, total, run_id, failures)

    print(f"\n✅ {total} failed test(s) on {the_date} across {len(failures)} class(es)")
    for c in sorted(failures):
        print(f"   {c.split('.')[-1]}: {len(failures[c])}")
    print(f"\n📄 suite:   {path}")
    print(f"🗂  history: {hist}")
    print(f"▶️  run locally: mvn test -DsuiteXmlFile={path}")


if __name__ == "__main__":
    main()
