#!/usr/bin/env python3
"""
Assertion Coverage Check — fails when @Test methods lack assertions.

Background
----------
A scan on 2026-04-30 found 373 of 1,252 @Test methods (29.8%) had ZERO
assertions: no assertTrue/assertFalse/assertEquals/assertNotNull/fail/throw,
no logFail. These tests cannot fail in CI regardless of product behavior —
they're "pass anyway" stubs documented as an anti-pattern in the project's
own SDET prompt template (see docs/ai-features-changelog/041, 045).

This script enforces "no NEW pass-anyway tests" by:
  1. Scanning every src/test/java/com/egalvanic/tests/*Test*.java for @Test methods
  2. Checking each method body for at least one assertion / fail / throw / SkipException
  3. Comparing against scripts/assertion-baseline.txt (the 373 grandfathered tests)
  4. Exit non-zero if a NEW @Test method has no assertion

Usage
-----
  # Local: print findings
  python3 scripts/check_assertion_coverage.py

  # CI gate (exit non-zero on failure)
  python3 scripts/check_assertion_coverage.py --strict

  # Regenerate baseline (after deliberately accepting new pass-anyway tests — rare)
  python3 scripts/check_assertion_coverage.py --update-baseline

The baseline lives at scripts/assertion-baseline.txt with one identifier per
line in the format "FileName.java::testMethodName". The intent is the
baseline shrinks over time as legitimate assertions are added — never grow.
"""

import argparse
import glob
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_GLOB = "src/test/java/com/egalvanic/tests/*Test*.java"
BASELINE_FILE = REPO_ROOT / "scripts" / "assertion-baseline.txt"

# Patterns that count as "this test can actually fail"
ASSERTION_PATTERNS = (
    "assertTrue(",
    "assertFalse(",
    "assertEquals(",
    "assertNotNull(",
    "assertNull(",
    "assertSame(",
    "assertNotSame(",
    "fail(",
    "Assert.fail(",
    "throw new ",
    "SkipException",
    "logFail(",
    "logFailure(",
    "logCriticalFailure(",
    "reportTestFailure(",
)

TEST_METHOD_RE = re.compile(
    r"@Test\([^)]*\)\s*public\s+void\s+(\w+)\s*\(\s*\)\s*\{",
    re.MULTILINE,
)


def find_method_body(src: str, body_start: int) -> str:
    """Given the index right after `{`, return the method body as a string."""
    depth = 1
    i = body_start
    while i < len(src) and depth > 0:
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    return src[body_start : i - 1]


def scan_repo() -> list[tuple[str, str]]:
    """Return list of (filename, methodName) for all @Test methods that have NO assertion."""
    findings: list[tuple[str, str]] = []
    test_files = sorted(glob.glob(str(REPO_ROOT / TESTS_GLOB)))
    for path in test_files:
        with open(path, encoding="utf-8") as f:
            src = f.read()
        for match in TEST_METHOD_RE.finditer(src):
            method_name = match.group(1)
            body = find_method_body(src, match.end())
            if not any(pat in body for pat in ASSERTION_PATTERNS):
                findings.append((os.path.basename(path), method_name))
    return findings


def load_baseline() -> set[str]:
    """Return baseline as a set of "File.java::methodName" identifiers."""
    if not BASELINE_FILE.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    }


def write_baseline(findings: list[tuple[str, str]]) -> None:
    BASELINE_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# scripts/assertion-baseline.txt",
        "# Grandfathered list of @Test methods that have no assertions.",
        "# Generated by scripts/check_assertion_coverage.py.",
        "# NEW @Test methods MUST have at least one assertion — this list is",
        "# allowed to shrink only. Adding entries here requires explicit review.",
        f"# Generated: {len(findings)} entries.",
        "",
    ]
    lines.extend(f"{fn}::{mn}" for fn, mn in sorted(findings))
    BASELINE_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero if any NEW pass-anyway test is found",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Regenerate the baseline file from current state (use with caution)",
    )
    args = parser.parse_args()

    findings = scan_repo()
    findings_set = {f"{fn}::{mn}" for fn, mn in findings}

    if args.update_baseline:
        write_baseline(findings)
        print(f"Wrote baseline: {len(findings)} entries → {BASELINE_FILE}")
        return 0

    baseline = load_baseline()

    new_pass_anyway = findings_set - baseline
    fixed_since_baseline = baseline - findings_set

    print(f"Total @Test methods scanned: ~1,252 (across {len(set(fn for fn, _ in findings))} files)")
    print(f"Currently pass-anyway:        {len(findings)}")
    print(f"Baseline (grandfathered):     {len(baseline)}")
    print(f"NEW pass-anyway (regressions): {len(new_pass_anyway)}")
    print(f"Fixed since baseline:          {len(fixed_since_baseline)}")
    print()

    if fixed_since_baseline:
        print(f"✅ Tests fixed since baseline ({len(fixed_since_baseline)}):")
        for ident in sorted(fixed_since_baseline)[:20]:
            print(f"   - {ident}")
        if len(fixed_since_baseline) > 20:
            print(f"   ... and {len(fixed_since_baseline) - 20} more")
        print()

    if new_pass_anyway:
        print(f"❌ NEW pass-anyway tests detected ({len(new_pass_anyway)}):")
        for ident in sorted(new_pass_anyway):
            print(f"   - {ident}")
        print()
        print("These @Test methods have no assertion / fail() / throw / SkipException.")
        print("They will report PASS regardless of whether the product works correctly.")
        print()
        print("Fix by adding at least one assertion that ties the PASS verdict to a real")
        print("product behavior. If the test is intentionally a setup/teardown helper,")
        print("rename it (don't use @Test) or add it to scripts/assertion-baseline.txt")
        print("with a comment explaining why.")
        if args.strict:
            return 1

    if not new_pass_anyway and not fixed_since_baseline:
        print("No regressions, no fixes — baseline state unchanged.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
